"""Guardrails: reliability and oversight (a graded pattern).

  1. Input guard   — refuse advice-seeking prompts ("should I buy X?") with a helpful redirect. Cheap
                     keyword pass first; the FAST model adjudicates borderline cases.
  2. Output guard  — every factual sentence in the report must carry a citation [n] that maps to a real
                     source in the workspace; disclaimer must be present; no forbidden phrasing
                     ("you should buy", "guaranteed").
  3. Weight guard  — scenario weights must be normalised, within tilt limits unless the critic signed off.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field

from .tools import calculator as calc

ADVICE_PATTERNS = [
    r"\bshould i (buy|sell|short|hold|invest)\b", r"\bis (it|[A-Za-z.]{1,6}) a (good|bad|great|smart) (buy|investment|stock to buy)\b",
    r"\bworth (buying|selling|investing in)\b", r"\bgood time to (buy|sell)\b",
    r"\b(buy|sell) (or|vs\.?) (sell|buy)\b\??$", r"\bwhat should i do with my\b", r"\btell me (to|whether to) (buy|sell)\b",
    r"\bwill (it|the stock|[A-Z]{1,5}) go (up|down)\b", r"\bguaranteed\b",
]
FORBIDDEN_OUTPUT = [r"\byou should (buy|sell|short)\b", r"\bguaranteed\b", r"\bcan'?t lose\b", r"\bsure thing\b",
                    r"\bI recommend (buying|selling)\b"]
DISCLAIMER = ("*The Second Opinion is a research-synthesis tool. This report is generated by AI from public sources "
              "and is **not investment advice**. Verify all figures against primary sources before making decisions.*")

REFUSAL = ("I can't tell you whether to buy or sell — that depends on your goals, horizon, and risk tolerance, and "
           "The Second Opinion is a research tool, not an adviser. What I can do is lay out the evidence: run a full "
           "report on the ticker (bull case, bear case, sourced metrics, scenario valuation) or ask a focused "
           "question like \"what are the biggest risks in the latest 10-K?\"")


@dataclass
class GuardResult:
    ok: bool
    reason: str = ""
    details: dict = field(default_factory=dict)


def input_guard(query: str, llm=None) -> GuardResult:
    q = query.strip()
    for pat in ADVICE_PATTERNS:
        if re.search(pat, q, re.I):
            return GuardResult(False, "advice_seeking", {"matched": pat, "response": REFUSAL})
    if llm is not None and len(q.split()) > 3:
        try:
            verdict = llm.complete_json(
                "Classify this user request for an equity-research tool. Reply JSON {\"advice_seeking\": true|false}. "
                "advice_seeking=true ONLY if the user is asking for a personal buy/sell/hold recommendation or a "
                "guarantee about future price. Asking for analysis, risks, valuation scenarios, or facts is false.\n\n"
                f"Request: {q}", tier="fast", max_tokens=50)
            if verdict.get("advice_seeking") is True:
                return GuardResult(False, "advice_seeking", {"matched": "llm", "response": REFUSAL})
        except Exception:  # noqa: BLE001 — guard must never crash the run
            pass
    return GuardResult(True)


_CITE = re.compile(r"\[(\d+)\]")
_SENT_SPLIT = re.compile(r"(?<=[.!?])\s+(?=[A-Z(\*])")


def _factual_sentences(md: str) -> list[str]:
    """Sentences that plausibly state a checkable fact: contain a digit or a %/$ sign or a strong verb."""
    out = []
    for raw in md.splitlines():
        line = raw.strip()
        if not line or line.startswith(("#", "|", "---", "*The Second Opinion", "**Sources", "[", "> ")):
            continue
        line = re.sub(r"^[-*\d.]+\s+", "", line)
        for s in _SENT_SPLIT.split(line):
            s = s.strip()
            if len(s) < 25:
                continue
            if re.search(r"\d|%|\$", s) or re.search(r"\b(is|are|was|were|has|have|added|rose|fell|grew|declined|reported|guided)\b", s):
                out.append(s)
    return out


def output_guard(report_md: str, n_sources: int, *, min_coverage: float = 0.9) -> GuardResult:
    sents = _factual_sentences(report_md)
    cited = [s for s in sents if _CITE.search(s)]
    coverage = (len(cited) / len(sents)) if sents else 1.0
    bad_refs = sorted({int(n) for n in _CITE.findall(report_md) if int(n) < 1 or int(n) > n_sources})
    forbidden = [p for p in FORBIDDEN_OUTPUT if re.search(p, report_md, re.I)]
    has_disclaimer = "not investment advice" in report_md.lower()
    uncited = [s for s in sents if not _CITE.search(s)][:5]
    ok = coverage >= min_coverage and not bad_refs and not forbidden and has_disclaimer
    reasons = []
    if coverage < min_coverage:
        reasons.append(f"citation coverage {coverage:.0%} < {min_coverage:.0%}")
    if bad_refs:
        reasons.append(f"citations to non-existent sources: {bad_refs}")
    if forbidden:
        reasons.append("forbidden advice phrasing present")
    if not has_disclaimer:
        reasons.append("disclaimer missing")
    return GuardResult(ok, "; ".join(reasons), {"coverage": round(coverage, 3), "n_factual": len(sents),
                                                "n_cited": len(cited), "bad_refs": bad_refs, "forbidden": forbidden,
                                                "has_disclaimer": has_disclaimer, "uncited_examples": uncited})


def weight_guard(weights: dict[str, float], critic_signed_off: bool) -> GuardResult:
    w = calc.normalize_weights(weights)
    tilt = calc.weight_tilt(w)
    if tilt > calc.MAX_TILT and not critic_signed_off:
        return GuardResult(False, f"weight tilt {tilt:.2f} exceeds {calc.MAX_TILT} without critic sign-off", {"weights": w, "tilt": tilt})
    return GuardResult(True, "", {"weights": w, "tilt": tilt})


def ensure_disclaimer(report_md: str) -> str:
    return report_md if "not investment advice" in report_md.lower() else report_md.rstrip() + "\n\n---\n" + DISCLAIMER + "\n"
